version: '3.8'

services:
  # 1. قاعدة البيانات
  db:
    image: postgres:17-alpine
    container_name: btec-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btec_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. الخلفية (Backend)
  backend:
    build: ./backend
    container_name: btec-backend
    ports:
      - "10000:10000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/btec_db
    restart: always
    depends_on:
      - db

  # 3. الواجهة (Frontend)
  frontend:
    build: ./frontend
    container_name: btec-frontend
    ports:
      - "3000:3000"
    environment:
      # نستخدم localhost لأن المتصفح هو من سينفذ الطلب من جهازك الشخصي
      - NEXT_PUBLIC_API_URL=http://localhost:10000
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: